/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PrivateIdentityRegistry } from "./PrivateIdentityRegistry";
export type { PrivateIdentityRegistryExample } from "./PrivateIdentityRegistryExample";
