/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StringTestsContract } from "./StringTestsContract";
export type { TestMpcCore } from "./TestMpcCore";
