/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PrivateAuction__factory } from "./PrivateAuction__factory";
export { PrivateAuctionExample__factory } from "./PrivateAuctionExample__factory";
