/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as precompiles from "./precompiles";
export { DataOnChain__factory } from "./DataOnChain__factory";
export { OnChainDatabase__factory } from "./OnChainDatabase__factory";
export { PrivateAuction__factory } from "./PrivateAuction__factory";
export { PrivateIdentityRegistry__factory } from "./PrivateIdentityRegistry__factory";
export { PrivateNFT__factory } from "./PrivateNFT__factory";
export { PrivateToken__factory } from "./PrivateToken__factory";
