/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PrivateAuction } from "./PrivateAuction";
export type { PrivateAuctionExample } from "./PrivateAuctionExample";
