/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PrivateIdentityRegistry__factory } from "./PrivateIdentityRegistry__factory";
export { PrivateIdentityRegistryExample__factory } from "./PrivateIdentityRegistryExample__factory";
